CREATE TABLE IF NOT EXISTS misc (
    key VARCHAR PRIMARY KEY,
    value VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS tickets (
    id INTEGER PRIMARY KEY NOT NULL,
    category VARCHAR NOT NULL,
    ownerId VARCHAR NOT NULL,
    locale VARCHAR NOT NULL,
    info VARCHAR NOT NULL,
    createdAt BIGINT NOT NULL,
    claimedAt BIGINT NOT NULL,
    closedAt BIGINT DEFAULT NULL,
    channelId VARCHAR DEFAULT '' NOT NULL,
    supporterId VARCHAR DEFAULT '' NOT NULL,
    closerId VARCHAR DEFAULT '' NOT NULL
);