appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%highlight{%d{yy/MM/dd HH:mm:ss} %p %c{2}: %m%n}{FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=blue, TRACE=gray}
rootLogger.level=debug
rootLogger.appenderRef.stdout.ref=STDOUT