name: Build the bot
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'
      - name: Build everything with Gradle
        run: gradle shadowJar

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: discord-ticketbot
          path: ./build/libs/discord-ticketbot-all.jar